### ISSUE TITLE
CWrapFile should have write member function

### ISSUE THREAD

**Issue by stefoss23** [Statoil/cwrap#18]
This used to be possible before:

 with open("grid.grdecl" , "w") as f2:
     f2.write("SPECGRID\n")
     f2.write("  10  10  10  \'F\' /\n")
     coord_kw = f["COORD"][0]
     coord_kw.write_grdecl( f2 )

Now it isn't. 
open cannot be exhanged with copen, because  CWrapFIle does not have a "write" member function.

**Comment by joakim-hove** [comment]
> [...] Now it isn't.

That is true - and it is unfortunate; but that was the price to pay to get Python3 support.
