### ISSUE TITLE
windows python3.6 import error

### ISSUE THREAD

**Issue by joylin1984** [Statoil/cwrap#25]
import cwrap
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-7-0a8d00ab8c54> in <module>()
----> 1 import cwrap

D:\WPy-x64-3662\python-3.6.6.amd64\lib\site-packages\cwrap\__init__.py in <module>()
     44 from .basecvalue import BaseCValue
     45 
---> 46 from .cfile import CFILE, copen as open
     47 from .clib import load, lib_name
     48 

D:\WPy-x64-3662\python-3.6.6.amd64\lib\site-packages\cwrap\cfile.py in <module>()
     89     from .clib import load as cwrapload
     90 
---> 91     class LibcPrototype(Prototype):
     92         lib = cwrapload(None)
     93 

D:\WPy-x64-3662\python-3.6.6.amd64\lib\site-packages\cwrap\cfile.py in LibcPrototype()
     90 
     91     class LibcPrototype(Prototype):
---> 92         lib = cwrapload(None)
     93 
     94         def __init__(self, prototype, bind=False, allow_attribute_error=False):

D:\WPy-x64-3662\python-3.6.6.amd64\lib\site-packages\cwrap\clib.py in load(lib, so_version, path, so_ext)
    107 # """ % LD_LIBRARY_PATH
    108 #     raise ImportError(error_msg)

ImportError: 
Failed to load shared library:None

dlopen() error: LoadLibrary() argument 1 must be str, not None

**Comment by joakim-hove** [comment]
Ok - thank you for the report. Is the full trace back? I would assume it started somewhere in libecl.

**Comment by joylin1984** [comment]
> Ok - thank you for the report. Is the full trace back? I would assume it started somewhere in libecl.

Contrast tests were done in python 2. 7, all without libecl. 
It works on python2.7.

**Comment by joakim-hove** [comment]
> Contrast tests were done in python 2. 7, all without libecl.
> It works on python2.7.

OK - sorry if I am a bit dim; I get the feeling the code you are running is just:
```python
>>> import cwrap
```
is that correct? If not - can you please post (an excerpt) of the code you are actually running. I would very much like this to work, but it should be said that on a daily basis Python2.7 and Linux is the main platform - so you are on a far-less-tested platform.

**Comment by joylin1984** [comment]
I am a novice programmer.
with winpython3.6.6.2 , cwrap master newwest.
yes, only "import cwrap".
```
D:\WPy-x64-3662\scripts>python
Python 3.6.6 (v3.6.6:4cf1f54eb7, Jun 27 2018, 03:37:03) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import cwrap
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\WPy-x64-3662\python-3.6.6.amd64\lib\site-packages\cwrap\__init__.py", line 46, in <module>
    from .cfile import CFILE, copen as open
  File "D:\WPy-x64-3662\python-3.6.6.amd64\lib\site-packages\cwrap\cfile.py", line 91, in <module>
    class LibcPrototype(Prototype):
  File "D:\WPy-x64-3662\python-3.6.6.amd64\lib\site-packages\cwrap\cfile.py", line 92, in LibcPrototype
    lib = cwrapload(None)
  File "D:\WPy-x64-3662\python-3.6.6.amd64\lib\site-packages\cwrap\clib.py", line 108, in load
    raise ImportError(error_msg)
ImportError:
Failed to load shared library:None

dlopen() error: LoadLibrary() argument 1 must be str, not None

The runtime linker has searched through the default location of shared
libraries, and also the locations mentioned in your LD_LIBRARY_PATH
variable. Your current LD_LIBRARY_PATH setting is:

   LD_LIBRARY_PATH: D:\Python\Python_Learning\libecl-master\bb\lib\python3.6\site-packages\ecl\lib

You might need to update this variable?
```

**Comment by joakim-hove** [comment]
I am sorry this is taking so long - I am struggling to get hold of a Window+Python3.6 installation.

**Comment by joylin1984** [comment]
Hi, joakim. 
I tried to fix this bug many times, but all failed :(
If you have time, I look forward to seeing you fix this bug.
Many thanks!

**Comment by andreabrambilla** [comment]
@joakim-hove I managed to get that installed and I can reproduce the issue, I'll look into it tomorrow ;)

**Comment by andreabrambilla** [comment]
Hopefully fixed by this https://github.com/Statoil/cwrap/pull/26
