### ISSUE TITLE
ArgumentError has no message attribute

### ISSUE THREAD

**Issue by eivindjahren** [Statoil/cwrap#30]
On python 3.6 https://github.com/equinor/cwrap/blob/f5cd74913d7e77a5fe14fea11190e8e61057b37e/cwrap/prototype.py#L226 will cause an `AttributeError: ArgumentError object has no attribute 'message'.`

**Comment by valentin-krasontovitsch** [comment]
still hitting this as `another exception occured...` - i'm sorry, how was this completed? is this will not fix?

**Comment by valentin-krasontovitsch** [comment]
and after experimenting with a fix locally, i can see that it actually stops me from getting a meaningful error message. reopening.
